//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPro.Common.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoPro.Common.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e013.
        /// </summary>
        public static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e001.
        /// </summary>
        public static string UserMsg_AccountEmpty {
            get {
                return ResourceManager.GetString("UserMsg_AccountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e005.
        /// </summary>
        public static string UserMsg_DateOfBirthLongerNow {
            get {
                return ResourceManager.GetString("UserMsg_DateOfBirthLongerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e008.
        /// </summary>
        public static string UserMsg_DuplicateAccount {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e009.
        /// </summary>
        public static string UserMsg_DuplicateEmail {
            get {
                return ResourceManager.GetString("UserMsg_DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e004.
        /// </summary>
        public static string UserMsg_EmailEmpty {
            get {
                return ResourceManager.GetString("UserMsg_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e006.
        /// </summary>
        public static string UserMsg_EmailRegex {
            get {
                return ResourceManager.GetString("UserMsg_EmailRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e003.
        /// </summary>
        public static string UserMsg_FullNameEmpty {
            get {
                return ResourceManager.GetString("UserMsg_FullNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e011.
        /// </summary>
        public static string UserMsg_GetByIDFail {
            get {
                return ResourceManager.GetString("UserMsg_GetByIDFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e010.
        /// </summary>
        public static string UserMsg_LoginFail {
            get {
                return ResourceManager.GetString("UserMsg_LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e002.
        /// </summary>
        public static string UserMsg_PasswordEmpty {
            get {
                return ResourceManager.GetString("UserMsg_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e007.
        /// </summary>
        public static string UserMsg_PasswordMaxlength {
            get {
                return ResourceManager.GetString("UserMsg_PasswordMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e012.
        /// </summary>
        public static string UserMsg_ServerError {
            get {
                return ResourceManager.GetString("UserMsg_ServerError", resourceCulture);
            }
        }
    }
}
